# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-14 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='account',
        ),
        migrations.AlterField(
            model_name='toilet',
            name='toilet_tag',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
