# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-14 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitation', '0002_auto_20191014_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='toilet_tag',
            field=models.TextField(default='', max_length=30),
        ),
    ]
