# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-14 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanitation', '0003_auto_20191014_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='id',
        ),
        migrations.AddField(
            model_name='bills',
            name='payment',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sanitation.Payment'),
        ),
    ]
